"""Concrete preprocessing adapters for live inference."""

from .preprocessing_config import (
    BrightnessNormalizationRuntimeConfig,
    TriStreamPreprocessingConfig,
)
from .foreground_policy import (
    DEFAULT_FOREGROUND_EXTRACTION_MODE,
    LEGACY_SILHOUETTE_FOREGROUND_EXTRACTION_MODE,
    SUPPORTED_FOREGROUND_EXTRACTION_MODES,
    ForegroundExtractionPolicySnapshot,
    ForegroundExtractionPolicyState,
    normalize_foreground_extraction_mode,
)
from .camera_intrinsics import (
    CAMERA_INTRINSICS_METADATA_APPLIED,
    CAMERA_INTRINSICS_METADATA_MODE,
    CAMERA_INTRINSICS_METADATA_REVISION,
    CAMERA_INTRINSICS_MODE_DISABLED,
    CAMERA_INTRINSICS_MODE_LABELS,
    CAMERA_INTRINSICS_MODE_REAL_TO_UNITY_INTRINSICS_REMAP,
    CAMERA_INTRINSICS_MODE_REAL_UNDISTORT_ONLY,
    SUPPORTED_CAMERA_INTRINSICS_MODES,
    CameraCalibration,
    CameraIntrinsicsFrameTransformer,
    CameraIntrinsicsTransformResult,
    CameraIntrinsicsTransformSnapshot,
    CameraIntrinsicsTransformState,
    default_real_calibration_path,
    default_unity_calibration_path,
    normalize_camera_intrinsics_mode,
)
from .roi_fcn_locator import (
    RoiFcnArtifactMetadata,
    RoiFcnLocator,
    decode_roi_fcn_heatmap,
    load_roi_fcn_artifact_metadata,
    resolve_roi_fcn_checkpoint,
)
from .roi_locator import (
    RoiFcnLocatorInput,
    RoiLocation,
    RoiLocator,
    build_roi_fcn_exclusion_mask,
    build_roi_fcn_locator_input,
    build_roi_locator_input_representation,
)
from .locators import (
    BackgroundEdgeLocator,
    BackgroundEdgeLocatorConfig,
    FixedCenterRoiLocator,
    LocatorRuntimeParameterState,
    ManualFixedRoiLocator,
    RoiFcnLegacyLocatorAdapter,
    build_locator,
)
from .stage_policy import (
    DIAGNOSTIC_PROFILE_BASELINE_INVERTED_MASKED_LOCATOR,
    ROI_LOCATOR_INPUT_MODE_AS_IS,
    ROI_LOCATOR_INPUT_MODE_INVERTED,
    ROI_LOCATOR_INPUT_MODE_SHEET_DARK_FOREGROUND,
    ROI_LOCATOR_INPUT_POLARITY_AS_IS,
    ROI_LOCATOR_INPUT_POLARITY_INVERTED,
    SUPPORTED_DIAGNOSTIC_PROFILES,
    SUPPORTED_ROI_LOCATOR_INPUT_MODES,
    SUPPORTED_ROI_LOCATOR_INPUT_POLARITIES,
    StageTransformPolicySnapshot,
    StageTransformPolicyState,
    diagnostic_profile_updates,
    normalize_diagnostic_profile_name,
    normalize_roi_locator_input_mode,
    normalize_roi_locator_input_polarity,
)
from .generic_tri_stream_live_preprocessor import (
    LocatorDiagnosticResult,
    PreprocessingDebugError,
    RoiRejectedError,
    TriStreamLivePreprocessor,
)

RoiLocatorDiagnosticResult = LocatorDiagnosticResult

__all__ = [
    "BrightnessNormalizationRuntimeConfig",
    "BackgroundEdgeLocator",
    "BackgroundEdgeLocatorConfig",
    "CAMERA_INTRINSICS_METADATA_APPLIED",
    "CAMERA_INTRINSICS_METADATA_MODE",
    "CAMERA_INTRINSICS_METADATA_REVISION",
    "CAMERA_INTRINSICS_MODE_DISABLED",
    "CAMERA_INTRINSICS_MODE_LABELS",
    "CAMERA_INTRINSICS_MODE_REAL_TO_UNITY_INTRINSICS_REMAP",
    "CAMERA_INTRINSICS_MODE_REAL_UNDISTORT_ONLY",
    "CameraCalibration",
    "CameraIntrinsicsFrameTransformer",
    "CameraIntrinsicsTransformResult",
    "CameraIntrinsicsTransformSnapshot",
    "CameraIntrinsicsTransformState",
    "FixedCenterRoiLocator",
    "ForegroundExtractionPolicySnapshot",
    "ForegroundExtractionPolicyState",
    "LocatorDiagnosticResult",
    "LocatorRuntimeParameterState",
    "ManualFixedRoiLocator",
    "RoiFcnArtifactMetadata",
    "RoiFcnLocatorInput",
    "RoiFcnLocator",
    "RoiLocatorDiagnosticResult",
    "RoiLocation",
    "RoiLocator",
    "RoiFcnLegacyLocatorAdapter",
    "RoiRejectedError",
    "PreprocessingDebugError",
    "DEFAULT_FOREGROUND_EXTRACTION_MODE",
    "DIAGNOSTIC_PROFILE_BASELINE_INVERTED_MASKED_LOCATOR",
    "LEGACY_SILHOUETTE_FOREGROUND_EXTRACTION_MODE",
    "ROI_LOCATOR_INPUT_MODE_AS_IS",
    "ROI_LOCATOR_INPUT_MODE_INVERTED",
    "ROI_LOCATOR_INPUT_MODE_SHEET_DARK_FOREGROUND",
    "ROI_LOCATOR_INPUT_POLARITY_AS_IS",
    "ROI_LOCATOR_INPUT_POLARITY_INVERTED",
    "StageTransformPolicySnapshot",
    "StageTransformPolicyState",
    "SUPPORTED_CAMERA_INTRINSICS_MODES",
    "SUPPORTED_FOREGROUND_EXTRACTION_MODES",
    "SUPPORTED_DIAGNOSTIC_PROFILES",
    "SUPPORTED_ROI_LOCATOR_INPUT_MODES",
    "SUPPORTED_ROI_LOCATOR_INPUT_POLARITIES",
    "TriStreamLivePreprocessor",
    "TriStreamPreprocessingConfig",
    "build_locator",
    "build_roi_fcn_exclusion_mask",
    "build_roi_fcn_locator_input",
    "build_roi_locator_input_representation",
    "decode_roi_fcn_heatmap",
    "default_real_calibration_path",
    "default_unity_calibration_path",
    "diagnostic_profile_updates",
    "load_roi_fcn_artifact_metadata",
    "normalize_camera_intrinsics_mode",
    "normalize_diagnostic_profile_name",
    "normalize_foreground_extraction_mode",
    "normalize_roi_locator_input_mode",
    "normalize_roi_locator_input_polarity",
    "resolve_roi_fcn_checkpoint",
]
